# -*- coding: utf-8 -*-
"""BDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MDd-PXTuiruEI4fyCG0goDJU2FwJlj8Q
"""

from google.colab import drive
drive.mount('/content/drive')

"""#Data Set"""

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("/content/drive/MyDrive/BDA/results.csv")
df.head()

"""#Data Cleaning"""

df.dropna()

"""#Importing the Libraries
 
"""

import seaborn as sns
from wordcloud import WordCloud
import matplotlib.pyplot as plt

df['_map'].head(10)

count = df['_map'].value_counts()

count = pd.DataFrame(count)

count

count.plot.bar()

df['team_1'].head(10)

team_count = df['team_1'].value_counts().head(15)

team_count

team_count = pd.DataFrame(team_count)

team_count

team_count.plot.bar()

df.head(15).plot.scatter('team_1','_map',figsize=(15,7))

df.tail(15).plot.scatter('_map','team_2',figsize=(15,7))

dust2 = df.loc[df['_map'] == "Dust2"]

